source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

target 'librato-iOS Demo' do
  pod 'librato-iOS', :path => '../librato-iOS.podspec'

  target 'librato-iOS DemoTests' do
      inherit! :search_paths
  end
end
